services:
  wiki:
    build:
      context: .
      args:
        MW_VERSION: ${MW_VERSION}
        PHP_VERSION: ${PHP_VERSION}
        DB_TYPE: ${DB_TYPE}
    image: ${IMAGE_NAME}

  mysql:
    image: ${DB_IMAGE}
    environment:
      - MYSQL_ROOT_PASSWORD=database
    profiles:
      - mysql

  wait-for:
    image: mintel/docker-wait-for-it
    profiles:
      - no-up
