services:
  wiki:
    build:
      context: .
      args:
        MW_VERSION: ${MW_VERSION}
        PHP_VERSION: ${PHP_VERSION}
    image: ${IMAGE_NAME}

  mysql:
    image: ${DB_IMAGE:-mysql:5}
    environment:
      - MYSQL_ROOT_PASSWORD=database
    profiles:
      - mysql

  postgres:
    image: ${DB_IMAGE:-postgres:15}
    environment:
      - POSTGRES_PASSWORD=database
    profiles:
      - postgres

  wait-for:
    image: mintel/docker-wait-for-it
    profiles:
      - no-up
