name: Update Submodules

on:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          
      - name: Update submodules
        id: update
        run: |
          # Update submodules
          git submodule update --init --remote

          # Collect commit IDs for each submodule
          COMMIT_IDS=$(git submodule foreach --quiet 'echo $path: $(git rev-parse HEAD)')

          echo -e "Submodule commits:\n${COMMIT_IDS}"

          # Check for changes
          git status --porcelain
          if [ -n "$(git status --porcelain)" ]; then
            echo "Submodule updates found"

            BRANCH_NAME="update-submodules-branch"

            # Delete the remote branch if it exists
            if git ls-remote --exit-code --heads origin $BRANCH_NAME; then
              echo "Deleting existing remote branch $BRANCH_NAME"
              git push origin --delete $BRANCH_NAME
            fi

            # Delete the local branch if it exists
            if git show-ref --verify --quiet refs/heads/$BRANCH_NAME; then
              echo "Deleting existing local branch $BRANCH_NAME"
              git branch -D $BRANCH_NAME
            fi

            # Set up Git identity
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"

            # Create a new branch and make changes
            git checkout -b $BRANCH_NAME
            git add .
            git commit -m "Update submodules to latest commits"
            git push origin $BRANCH_NAME

            # Create a Pull Request with submodule commit IDs in the title
            PR_TITLE="Update submodules to latest commits"
            PR_BODY="This PR updates all submodules to their latest commits:\n\n${COMMIT_IDS}"
            gh pr create --title "$PR_TITLE" --body "$PR_BODY" --base master --head $BRANCH_NAME
          else
            echo "No submodule updates found"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
